services:
  # EMAIL (TEMPORARILY VIA UNREGISTRY UNTIL UPSTREAM ARM BUILDS RESTORED)
  email:
    image: maddy:latest
    pull_policy: never
    restart: always
    depends_on:
      - rspamd
    ports:
      - 25:25
      - 465:465
      - 587:587
      - 993:993
      - 143:143
    volumes:
      - ../services/email:/data
      - ../services/caddy/certificates/acme-v02.api.letsencrypt.org-directory/figbert.com:/data/certs
    labels:
      - "com.centurylinklabs.watchtower.no-pull=true"
  rspamd:
    image: a16bitsysop/rspamd
    restart: always
    user: 1000:1000
    volumes:
      - ../services/rspamd:/var/lib/rspamd

  # CALENDAR+CONTACTS
  radicale:
    image: grepular/radicale:3
    command: ["--config", "/var/radicale/config.ini"]
    restart: always
    volumes:
      - ../services/radicale:/var/radicale

  # PASSWORDS
  bitwarden:
    image: vaultwarden/server:alpine
    restart: always
    volumes:
      - ../services/bitwarden:/data
    environment:
      - DOMAIN=https://vault.figbert.com
      - SHOW_PASSWORD_HINT=false
      - ADMIN_TOKEN=${VAULT_ADMIN_TOKEN}
